### PR TITLE
erlang/otp 20.3.8.8

### PR DESCRIPTION
**Pull request by c0b**
from https://github.com/erlang/otp/releases/tag/OTP-20.3.8.8

=== OTP-20.3.8.8 ===
tagged 6 hours ago · 2790 commits to master since this tag

Changed Applications:
- inets-6.5.2.4

### CODE REVIEW

**Comment by c0b** [comment]
I don't think so but I can reproduce `docker pull erlang:20` not working for amd64 right now;

similar problems happened before, call @yosifkit @tianon to have a look to current Docker Hub status, wonder does it have a public status page (like https://status.github.com) about its operation current status and all history?

https://github.com/docker-library/official-images#docker-official-images for @ryan-mahoney about details  on how are these official images being built

**Comment by tianon** [comment]
Looks like another casualty of https://github.com/docker-library/official-images/issues/4789. :disappointed:

I'll go fire off a temporary build to get the current issue resolved.

**Comment by c0b** [comment]
right, from your ticket I got the API access by:

```console
$ curl -s https://registry.hub.docker.com/v2/repositories/library/erlang/tags/20/ | ~/bin/jq
{
  "name": "20",
  "full_size": 429434615,
  "images": [
    {
      "size": 457354230,
      "architecture": "s390x",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 457140394,
      "architecture": "ppc64le",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 442563562,
      "architecture": "arm64",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    },
    {
      "size": 429434615,
      "architecture": "arm",
      "variant": null,
      "features": null,
      "os": "linux",
      "os_version": null,
      "os_features": null
    }
  ],
  "id": 13020340,
  "repository": 399020,
  "creator": 2215,
  "last_updater": 1156886,
  "last_updated": "2018-08-29T12:42:54.785791Z",
  "image_id": null,
  "v2": true
}
```

the 4 combinations do not have for amd64

      "architecture": "s390x",
      "architecture": "...",

**Comment by tianon** [comment]
Sorry for not getting back to this sooner -- this immediate issue should be long-since fixed now. :+1:

(and hopefully a fix for the bigger issue in https://github.com/docker-library/official-images/issues/4789 is in the very short future)

**Pull request merged**
