### PR TITLE
Added GitHub Actions

### PR DESCRIPTION
**Pull request by vkatsuba**
**Purpose of changes:**
* Migrate `CI/CD` to `GitHub Actions`
* Remove `.travis.yml `
* Remove `.gitlab-ci.yml`

**GitHub Actions Result** https://github.com/vkatsuba/docker-erlang-otp/runs/2509104795

**TODO**:
```
DIR=master
Error response from daemon: dockerfile parse error line 28: unknown instruction: @ECHO GitHub Actions
https://github.com/erlang/docker-erlang-otp/blob/master/master/Dockerfile#L28

DIR=master VARIANT=alpine
Error response from daemon: dockerfile parse error line 30: unknown instruction: @ECHO
https://github.com/erlang/docker-erlang-otp/blob/master/master/alpine/Dockerfile#L30
```

### CODE REVIEW

**Comment by getong** [comment]
Just ignore the master directory, it is fine.
The pr looks good to me.

**Comment by getong** [comment]
@garazdawi 
Would you open the github action of this repo? If you agree, I will merge this pr.

**Comment by vkatsuba** [comment]
@getong if all is ok with this PR, please ping me and I will remove `TODO`s and also `.travis.yml ` and `.gitlab-ci.yml` in separate commit for this PR.

**Comment by getong** [comment]
> @getong if all is ok with this PR, please ping me and I will remove `TODO`s and also `.travis.yml ` and `.gitlab-ci.yml` in separate commit for this PR.

You can do it now, and I will take care of other things. Thank you for your time.

**Comment by garazdawi** [comment]
> Would you open the github action of this repo? If you agree, I will merge this or.

I think that it is already open. Feel free to merge when you are happy with the PR.

**Comment by getong** [comment]
@vkatsuba 
As @garazdawi  agrees, and you can do whatever you like, I will merge this pr tomorrow.

**Comment by vkatsuba** [comment]
> @vkatsuba
> As @garazdawi agrees, and you can do whatever you like, I will merge this pr tomorrow.

Done. Thanks. Also updated `README` badge 'Build Status' - will be working after merge of PR.

**Pull request merged**
