### PR TITLE
OTP 24.0.3

### PR DESCRIPTION
**Pull request by vkatsuba**

### CODE REVIEW

**Comment by getong** [comment]
The master directory does not need to update frequently, please only update the 24 directory.

**Comment by vkatsuba** [comment]
> The master directory does not need to update frequently, please only update the 24 directory.

Done. Could you please tell - at what interval the `master` can be updated? I just thought that the `master` needs to be kept up to date on the same day when the OTP is updated, but seems it's not correct.

**Comment by getong** [comment]
> > The master directory does not need to update frequently, please only update the 24 directory.
> 
> Done. Could you please tell - at what interval the `master` can be updated? I just thought that the `master` needs to be kept up to date on the same day when the latest OTP version is updated, but seems it's not correct.

Only one time in a year. Because the master does not push to docker hub.

**Comment by vkatsuba** [comment]
> Only one time in a year. Because the master does not push to docker hub.

Got it, thanks.

**Pull request merged**
