### PR TITLE
erlang/otp 21.0 rc2

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by c0b** [comment]
I've just added you as collaborator, you can try merge yourself

this PR Looks Good ToMe :+1:

being a maintainer means more responsibility actually, not open the bump version PR(s), you can try make comments on other open issues / PRs, have your opinion is also welcome

**Comment by getong** [comment]
ok. I will be careful.

**Comment by getong** [comment]
@c0b Do you use git rebase operation? 
The github suggets me:
```
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b getong-erlang_21.0-rc2 master
git pull https://github.com/getong/docker-erlang-otp.git erlang_21.0-rc2
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff getong-erlang_21.0-rc2
git push origin master
```

**Comment by c0b** [comment]
from my use experience of git, I prefer the `--ff-only` to take the author's commit without a committer's commit;      rather than `--no-ff` would always create a committer's commit I don't like
When `--ff-only` refuses to merge it means something changed to master, or the commit wasn't created from latest master, in that case I would do a rebase.
The whole effect is to keep main development line straight;  in tools like `gitk`.

```console
$ git merge --ff-only getong-erlang_21.0-rc2
```

My experience with git dated since 2007 when the [`Tech Talk: Linus Torvalds on git`](https://www.youtube.com/watch?v=4XpnKHJAok8) was there, and a couple of git features were done by me during those early years;
not sure how Github Inc (which was only founded 2009) changed the culture to always to do merge commit (committer's commit),  it seems too late to tell Github Inc to change that behavior.

But when you're doing the merge, it's up to you;   I don't mind if people just click the merge button from the web which does a `--no-ff` merge commit.

**Pull request merged**
