### PR TITLE
chore: update to Alpine 3.20

### PR DESCRIPTION
**Pull request by mkonrad**

### CODE REVIEW

**Review by getong — CHANGES_REQUESTED** [review]
would you update it in 25, 26 directory?

**Comment by mkonrad** [comment]
Yes, I will update those too and re-submit.Sent from my iPhoneOn Nov 10, 2024, at 10:30, gerald ***@***.***> wrote:﻿
@getong requested changes on this pull request.

would you update it in 25, 26 directory?

**Comment by mkonrad** [comment]
Completed update for Erlang 25, 26, and 27.

Update to Alpine Linux v 3.20

### Erlang 25

    docker build -t aviumlabs/erlang:25-alpine .

    docker run -it --rm aviumlabs/erlang:25-alpine

>
> Erlang/OTP 25 [erts-13.2.2.10] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
>
> Eshell V13.2.2.10  (abort with ^G)
>

### Erlang 26

    docker build -t aviumlabs/erlang:26-alpine .

    docker run -it --rm aviumlabs/erlang:26-alpine

> 
> Erlang/OTP 26 [erts-14.2.5.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
> 
> Eshell V14.2.5.2 (press Ctrl+G to abort, type help(). for help)
> 


### Erlang 27

    docker build -t aviumlabs/erlang:27-alpine .

    docker run -it --rm aviumlabs/erlang:27-alpine

> 
> Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
> 
> Eshell V15.1.2 (press Ctrl+G to abort, type help(). for help)

**Comment by getong** [comment]
https://github.com/docker-library/official-images/pull/17877

**Pull request merged**
