### PR TITLE
update alpine to 3.13

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by garazdawi** [comment]
Just adding a note that this change is needed in order for https://github.com/docker-library/official-images/pull/9433 to be merged.

**Comment by getong** [comment]
@garazdawi 
The 21 branch can not be compiled due to the erlang/otp#2693.
Would you make a pr to merge this into 21 branch and make a new release?

**Comment by garazdawi** [comment]
> The 21 branch can not be compiled due to the erlang/otp#2693.

hmm, yes. I will see what I can do. It will not ready before Monday though.

**Comment by getong** [comment]
The commit hash is de870d7f9f36b3e68f280057851a4585a67ab219 .
You can chrry-pick it into erlang 21 branch.

**Comment by garazdawi** [comment]
Yes, finding the commit is not the problem. We are in the middle of physically moving all of the patch infrastructure so it will be down today and hopefully back on Monday :) You would think that doing a release might be as easy as just merging a commit to that branch, but alas it is not.

**Comment by garazdawi** [comment]
release done! I tested it with the OTP-21 dockerfile found here so it should work now.

**Comment by getong** [comment]
The 20 branch is need to cherry-pick 58632af80fd43955ec58c021e5c0d04caa1840de from maint.
@garazdawi

**Comment by garazdawi** [comment]
> The 20 branch is need to cherry-pick 58632af80fd43955ec58c021e5c0d04caa1840de , 2207e5248bbaf2961f179ddcc1dabbab292ca3c9 from maint.

We only support up to two major versions behind the current, that is 21, 22 and 23. I suggest that you do the same.

**Comment by getong** [comment]
The 20 alpine update to 3.12 .

**Pull request merged**
