### PR TITLE
stop support 17, update base os version to stretch

### PR DESCRIPTION
**Pull request by getong**
As in the docker-library/official-images#5036 , Debian Jessie has moved to LTS and no longer supports arm64v8, ppc64le, and s390x.
So just stop supporting 17, delete 21/jessie verison, and update the base os to stretch.
Feedback needed.

### CODE REVIEW

**Comment by areski** [comment]
@c0b Thanks for keeping us informed!

**Comment by getong** [comment]
erlang/otp 18.3.4.11 is included here.

**Comment by c0b** [comment]
and you want to cherry-pick the `OTP-20.3.8.13` from #177 and merge together?

**Comment by c0b** [comment]
seems erlang/docker-erlang-otp#130 docker-library/official-images#4995 all pending on this

**Comment by c0b** [comment]
I feel good with that

**Comment by getong** [comment]
I reset the HEAD~1,  and merge the pr.

**Pull request merged**
