### PR TITLE
add erlang/otp 24.0-rc1

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
@getong, is this the `rebar3` pre-built version (3.14.4)? If so, it's possible it won't work with OTP 24 due to the deprecation of `erlang:get_stacktrace/0` (and potentially other breaking changes).

**Comment by paulo-ferraz-oliveira** [comment]
@getong, did you get to read my previous comment?

**Comment by getong** [comment]
> @getong, did you get to read my previous comment?

I am waiting for the travis ci build result. If it is ok, I will merge it.

**Comment by getong** [comment]
> @getong, is this the `rebar3` pre-built version (3.14.4)? If so, it's possible it won't work with OTP 24 due to the deprecation of `erlang:get_stacktrace/0` (and potentially other breaking changes).

The travis ci build is ok, this function is not the reason.

**Comment by paulo-ferraz-oliveira** [comment]
Cool. I have to dig deeper into why we assumed there would be an issue.

**Comment by paulo-ferraz-oliveira** [comment]
Also, this is what @ferd wrote in the `rebar3` Slack and Twitter: "The pre-built version compiled with OTP-19 is not going to be compatible with OTP-24, you'll need to build from source in all likelihood."

**Comment by paulo-ferraz-oliveira** [comment]
I see. It might fail in failure situations :) 

This is the result of the pre-built `rebar3` running on OTP 24, when I call a function for a non-existing script.

```
rebar3 shell --script shell.escript
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling mylib
Erlang/OTP 24 [RELEASE CANDIDATE 1] [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [systemtap]

Eshell V12.0  (abort with ^G)
1> {"init terminating in do_boot",{undef,[{erlang,get_stacktrace,[],[]},{rebar3,main,1,[{file,"/home/runner/work/rebar3/rebar3/src/rebar3.erl"},{line,72}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{erlang,get_stacktrace,[],[]},{rebar3,main,1,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
```

It'll probably be OK for most cases, but otherwise, when it fails it'll be messy 😄

**Pull request merged**
