### PR TITLE
erlang/otp19.3.6.10 and 21.0.5

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by getong** [comment]
The build test fail log:
https://travis-ci.org/erlang/docker-erlang-otp/builds/414913311

The main problem is :
```
Err http://deb.debian.org/debian/ jessie/main odbcinst amd64 2.3.1-3
  Could not connect to cdn-fastly.deb.debian.org:80 (151.101.44.204), connection timed out
```
I will google it and try to resolve it.

**Comment by c0b** [comment]
the CI environment had some similar networking issues before, sometimes just kick it re-run might resolve;

since it passed CI,  should be good to merge

**Comment by tsloughter** [comment]
Are these autmatically published to the docker repo? I'm not finding `erlang:21.0.5-alpine` https://store.docker.com/images/erlang/plans/3f465305-b4af-4bb8-9a13-9ea13c89c937?tab=tags

**Comment by getong** [comment]
@tsloughter 
The images are pushed to the docker store after some time. It is not immediately done after the pr is merged. Wait for it, it is often ok.

**Comment by getong** [comment]
@tsloughter 
The pr is just now mrged, see 
https://github.com/docker-library/official-images/pull/4714

**Pull request merged**
