### PR TITLE
test erlang/otp 23.0-rc1

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by getong** [comment]
https://github.com/erlang/rebar3/commit/8ff256d5a8596879d6838774290503e48f9b7695
The rebar3 build failed, and rebar3 just needs a new tag.
@ferd @tsloughter

**Comment by ferd** [comment]
Yeah rebar3 is not ready for OTP-23 yet. We had a PR handling the conversion but it caused regression issues and we haven't heard back from the contributor nor had the time to fix it ourselves at this point in time.

**Comment by tsloughter** [comment]
I'll look at that today.

**Comment by tsloughter** [comment]
I'll look at that today.

**Comment by tsloughter** [comment]
Oh, but it is just a warning? so the issue would be resolved by removing "warnings_as_errors"?

I'd say just use `sed` to remove

```
,
            warnings_as_errors
```

From `rebar.config` before compiling in the Dockerfile for the time being.

**Comment by getong** [comment]
By using rebar3 3.13.1, it  works fine.

**Comment by getong** [comment]
@c0b 
I just notice that [julia](https://hub.docker.com/_/julia) has the rc version, and I think the erlang should have the same rc version for test, many developers can test erlang 23 by using the rc version, and the latest version is still point to 22.

**Comment by tsloughter** [comment]
Yea, should definitely have rc versions. Is something blocking that?

**Comment by getong** [comment]
Just wait for @c0b .

**Comment by tsloughter** [comment]
@getong oh, do we require @c0b to get our new versions? It has been harder to get a hold of them lately, we should not have a single person as a bottleneck for this.

**Comment by getong** [comment]
@c0b 
As this pr has been open for 7 days, and the test result is passed, and @tsloughter also agrees with me.
So I decide to merge this pr.

**Pull request merged**
