### PR TITLE
append zero string to verion if the verion is two digits

### LINKED ISSUE #291: For the future 23.1 use tag 23.1.0
@getong I'm opening this as a note in case I miss the future PR when 23.1 is released.

Discussing in the Build and Packaging Working Group led to the conclusion that the smallest change necessary to get others on board with using these images instead of duplicating work and causing community confusion would be to add that final `.0` to the version when a minor release is made. Also for a major release, meaning when 24 comes out the tags would be, `24`, `24.0` and `24.0.0`.

I realized I don't really know how the different versions are pushed and tagged. It is a manual process with a PR to add a new tag, like `23.1.0` and then how does it know to create `23` and `23.1` as well?

The `generate-stackbrew-library.sh` script outputs all the tags like:

```
Tags: 23.0.2, 23.0, 23, latest
Architectures: amd64, arm32v7, arm64v8, i386, s390x, ppc64le
GitCommit: ed3bd9400e1b72b2bdd08596990f8ed3350a75c0
Directory: 23
```

But travis only builds, it does not push, and then runs that `official-images/test/run.sh` with the image name/tag of the image built.

I don't see a push in that test script either but may have missed it if its calling out to other scripts in their official-images repo.

---

On a side note, we can move the manual process part to be a a github action as part of the `erlang/otp` repo. But we can worry about that after this.

### PR DESCRIPTION
**Pull request by getong**
fix #291

### CODE REVIEW

**Comment by ericmj** [comment]
Should two or maybe even three dots be added?

Are only `A.B` being overwritten on new releases or are `A.B.C` also being overwritten if there is a new `A.B.C.D` version?

**Comment by tsloughter** [comment]
Question is will there ever be a `X.0.0.Y`. I don't think that has ever happened or will ever happen. But we could do it to be safe.

And ask someone on the OTP team if they can guarantee no `X.0.0.Y`.

**Comment by tsloughter** [comment]
Ignore my comment, wasn't thinking. We do need to end up with 4 spots everywhere :(

**Comment by garazdawi** [comment]
Why not use two different tag names? one for the fixed tags and one for tags that follow the latest?

**Comment by tsloughter** [comment]
That is an option. I was going to suggest tag `:stable-23.0` to mean a 23.0 that doesn't move, but `stable` is probably confusing there as it might be interpreted to refer to if the Erlang/OTP release is "stable".

Is there a better word for `stable`?

**Comment by ericmj** [comment]
`:immutable-` maybe?

**Comment by tsloughter** [comment]
We discussed in the Build and Packaging WG this morning and `:immutable-` was preferred by those there.

If there aren't any objections I think we should go with that. So for every version an `:immutable-<vsn>` tag is created in addition to all the others and there is no need to modify the OTP version by adding any extra digits, just use the offiical version number.

**Comment by garazdawi** [comment]
Another approach would be to just to 21, 22, 23 as mutable versions and the  keep all other immutable. We only patch the latest 22.x release anyways so no need to have mutable 22.x versions as they would often be the same as 22.

**Comment by getong** [comment]
@tsloughter 
Do as you suggested.

**Comment by getong** [comment]
@tsloughter 
As 23.1 is released now, the solution might be adding a prefix `immutable-` before the exact version number. Like 23.1,  it might be another immutable-23.1 tag. If you do not have any other suggestion, this pr might be merged tomorrow(9.24 night).

**Comment by tsloughter** [comment]
@getong yea, I think `immutable-` was agreed on. So if you are ok with that that'd be great.

**Pull request merged**
